Fix #3: Added unit tests for reducers
BenMaruchu/public-web pull request #19
Opened 2018-06-04 07:33 UTC by mkumbobeaty

2018-06-05 15:51 UTC, BenMaruchu requested changes

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/index.test.js
> +describe('selectMapPoint reducer', () => {
Use correct reducer name i.e `SelectMapPoint Reducer`

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/index.test.js
> +    expect(state).toEqual(initialState);
You can use jest matcher `.toBeNull()` instead of using `toEqual()` can read more [here](https://facebook.github.io/jest/docs/en/expect.html)

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/index.test.js
> +  it('should handle SELECT_MAP_POINT', () => {
You are suppose to use an object not array in your action :expressionless:

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/index.test.js
> +    const prevState = undefined;
Use previous state as an object not undefined

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/index.test.js
> +  it('should return the initial state', () => {
Use describe for each reducer

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/index.test.js
> +    const prevState = undefined;
don't use undefined use an object or string based on the nature of reducer

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/index.test.js
> +  it('should handle SEARCH_TICKET_NUM_RESET', () => {
Previous state should not be equal to expect output in reset reducers cases

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/index.test.js
> +  it('should return the initial state for new SRsummary', () => {
Use describe here

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/serviceRequest.test.js
> +describe('serviceRequest reducer', () => {
Start with capital letter in describe reducer name

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/serviceRequest.test.js
> +  it('should return initial state', () => {
Update these initial state test to check for 
- [ ] call reducer with no args `reducer()`
- [ ] call reducer `reducer(undefined)`
- [ ] call reducer `reducer(undefined,{})`
- [ ] call reducer `reducer(undefined,{type:invalid})`

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/serviceRequest.test.js
> +  it('should add service requests to state', () => {
Separate these tests using blank line

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/serviceRequest.test.js
> +    const receiveServiceRequestState = [1, 2, 3];
Be consistent with your variables

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/statusFilter.test.js
> +  it('should handle RECEIVE_SR_SUMMARY', () => {
Refactor this

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/statusFilter.test.js
> +  });
Separate here with blank line

2018-06-05 15:51 UTC, BenMaruchu commented on src/reducers/__tests__/statusFilter.test.js
> +    const initialState = { statuses: [{ id: 1, name: 'unit' }] };
add `selected:true` field

2018-06-08 07:58 UTC, BenMaruchu requested changes
Remove /dist folder in public/ by running `npm run predev` this will prevent conflits once others decide to generate dist folder.

Make sure you pull from develop before push to the pull request after you have made required changes.

2018-06-08 08:16 UTC, mkumbobeaty commented
Done

On Fri, 8 Jun 2018 at 10:58, Benson Maruchu <notifications@github.com>
wrote:

> *@BenMaruchu* requested changes on this pull request.
>
> Remove /dist folder in public/ by running npm run predev this will
> prevent conflits once others decide to generate dist folder.
>
> Make sure you pull from develop before push to the pull request after you
> have made required changes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BenMaruchu/public-web/pull/19#pullrequestreview-127064981>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AT2pXYUCd4oj1a0J9T3iyJx4vzhZPqSHks5t6i68gaJpZM4UYlYt>
> .
>

2018-06-08 08:26 UTC, BenMaruchu approved these changes

2018-06-08 08:26 UTC, merged